= Lighting contracts without anchors

These contracts ignore the fees calculation, the dust limits and the
trimming of transactions. The purpose of these scripts is to show how
a complex lifecycle of transactions as observed in LN can be captured
with Bitcoin DSL.

These scripts also ignore the key derivation for various roles. We
initially generate a bunch of keys to fulfill the various roles.

* [x] Funding transaction
* [x] Commitment transaction without anchors
** [x] To Local
** [x] To Remote
** [x] Cooperative close after settling HTLCs
   This case is captured by the cooperative close without htlcs path.
** [x] Close unilaterally once all HTLCs are settled
   This case is captured by the cooperative close without htlcs path.
** [x] Add HTLCs
*** [x] HTLCs Offered
*** [x] HTLCs Received
** [x] Close unilaterally with unsettled HTLCs
*** [x] By local without penalty in time
*** [x] By local with penalty broadcast by remote
*** [x] By remote without penalty in time
*** [x] By remote with penalty broadcast by local
* [ ] HTLC Timeout & Success
* [ ] Revocation of commitments
* [ ] Closing Transaction
