# Copyright 2024 Kulpreet Singh
#
# This file is part of Bitcoin-DSL
#
# Bitcoin-DSL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bitcoin-DSL is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bitcoin-DSL. If not, see <https://www.gnu.org/licenses/>.

# frozen_string_literal: false

COMMANDS = [
  :getbestblockhash,
  :getblock,
  :getblockchaininfo,
  :getblockcount,
  :getblockfilter,
  :getblockhash,
  :getblockheader,
  :getblockstats,
  :getchaintips,
  :getchaintxstats,
  :getdifficulty,
  :getmempoolancestors,
  :getmempooldescendants,
  :getmempoolentry,
  :getmempoolinfo,
  :getrawmempool,
  :gettxout,
  :gettxoutproof,
  :gettxoutsetinfo,
  :preciousblock,
  :pruneblockchain,
  :savemempool,
  :scantxoutset,
  :verifychain,
  :verifytxoutproof,
  :getmemoryinfo,
  :getrpcinfo,
  :help,
  :logging,
  :stop,
  :uptime,
  :generateblock,
  :generatetoaddress,
  :generatetodescriptor,
  :getblocktemplate,
  :getmininginfo,
  :getnetworkhashps,
  :prioritisetransaction,
  :submitblock,
  :submitheader,
  :addnode,
  :clearbanned,
  :disconnectnode,
  :getaddednodeinfo,
  :getconnectioncount,
  :getnettotals,
  :getnetworkinfo,
  :getnodeaddresses,
  :getpeerinfo,
  :listbanned,
  :ping,
  :setban,
  :setnetworkactive,
  :analyzepsbt,
  :combinepsbt,
  :combinerawtransaction,
  :converttopsbt,
  :createpsbt,
  :createrawtransaction,
  :decodepsbt,
  :decoderawtransaction,
  :decodescript,
  :finalizepsbt,
  :fundrawtransaction,
  :getrawtransaction,
  :joinpsbts,
  :sendrawtransaction,
  :signrawtransactionwithkey,
  :testmempoolaccept,
  :utxoupdatepsbt,
  :createmultisig,
  :deriveaddresses,
  :estimatesmartfee,
  :getdescriptorinfo,
  :getindexinfo,
  :signmessagewithprivkey,
  :validateaddress,
  :verifymessage,
  :abandontransaction,
  :abortrescan,
  :addmultisigaddress,
  :backupwallet,
  :bumpfee,
  :createwallet,
  :dumpprivkey,
  :dumpwallet,
  :encryptwallet,
  :getaddressesbylabel,
  :getaddressinfo,
  :getbalance,
  :getbalances,
  :getnewaddress,
  :getrawchangeaddress,
  :getreceivedbyaddress,
  :getreceivedbylabel,
  :gettransaction,
  :getunconfirmedbalance,
  :getwalletinfo,
  :importaddress,
  :importdescriptors,
  :importmulti,
  :importprivkey,
  :importprunedfunds,
  :importpubkey,
  :importwallet,
  :keypoolrefill,
  :listaddressgroupings,
  :listlabels,
  :listlockunspent,
  :listreceivedbyaddress,
  :listreceivedbylabel,
  :listsinceblock,
  :listtransactions,
  :listunspent,
  :listwalletdir,
  :listwallets,
  :loadwallet,
  :lockunspent,
  :psbtbumpfee,
  :removeprunedfunds,
  :rescanblockchain,
  :send,
  :sendmany,
  :sendtoaddress,
  :sethdseed,
  :setlabel,
  :settxfee,
  :setwalletflag,
  :signmessage,
  :signrawtransactionwithwallet,
  :unloadwallet,
  :upgradewallet,
  :walletcreatefundedpsbt,
  :walletlock,
  :walletpassphrase,
  :walletpassphrasechange,
  :walletprocesspsb,
  :invalidateblock
]

BITCOIN_HASHES = %i[hash160 sha256 hmac_sha256 hmac_sha512].freeze
