#lang racket/base
;; Generates docs/reference/{forms,rules,opcodes}.md from the same describe
;; registry agents read over MCP, so the reference cannot drift from the
;; language. Run from racket-dsl/:  racket docs/gen-reference.rkt
;; tests/docs.rkt fails when the generated files are out of date.

(require racket/list
         racket/string
         racket/runtime-path
         bitcoin/conform)

(provide reference-pages)

(define-runtime-path reference-dir "reference")

(define header "<!-- Generated by docs/gen-reference.rkt from the describe registry. Do not edit by hand. -->\n\n")

(define (escape s) (string-replace (string-replace s "|" "\\|") "\n" " "))

(define (forms-page)
  (define groups
    '((definition "Definition forms" "Forms that bind names: chains, keys, contracts, transactions, rule sets.")
      (value "Values" "Constructors for amounts, locks, inputs, outputs and transactions.")
      (consensus "Consensus" "Composing and inspecting rule sets.")
      (session "Session" "Forms that change or test chain state.")
      (query "Queries" "Forms that read state and return data.")
      (conformance "Conformance" "Replay against real nodes (`#lang bitcoin/conform`).")))
  (string-append
   header
   "# Forms\n\n"
   "Every form the language exports for agents, grouped as `(describe)` groups them. "
   "Over MCP, `describe` with a form name returns the same usage and doc.\n\n"
   (string-append*
    (for/list ([g (in-list groups)])
      (string-append
       (format "## ~a\n\n~a\n\n" (second g) (third g))
       (string-append*
        (for/list ([f (in-list (describe (first g)))])
          (format "### `~a`\n\n```racket\n~a\n```\n\n~a\n\n" (first f) (second f) (third f)))))))))

(define (rules-page)
  (define entries (describe 'rules))
  (define-values (rules rest*) (splitf-at entries (λ (e) (memq '#:scope e))))
  (string-append
   header
   "# Consensus rules\n\n"
   "The rules of the `bitcoin` consensus value, in the order validation runs them. "
   "A rejection's `#:rule` is one of these names, or one of the script-level rules below.\n\n"
   "| Rule | Scope | What it checks |\n|---|---|---|\n"
   (string-append*
    (for/list ([r (in-list rules)])
      (format "| `~a` | ~a | ~a |\n" (first r) (third r) (escape (fourth r)))))
   "\n## Script-level rules\n\n"
   (escape (second (first rest*)))
   "\n\n| Rule | Meaning |\n|---|---|\n"
   (string-append*
    (for/list ([r (in-list (rest rest*))])
      (format "| `~a` | ~a |\n" (first r) (escape (second r)))))
   "\n## Proposal rules\n\n"
   "| Rule | Opcode | Meaning |\n|---|---|---|\n"
   (string-append*
    (for*/list ([name '(ctv)]
                [f (in-list (cadr (memq '#:failures (describe name))))])
      (format "| `~a` | `~a` | ~a |\n" (car f) name (escape (cdr f)))))))

(define (opcodes-page)
  (string-append
   header
   "# Opcodes\n\n"
   "Opcodes are identified by byte. Scripts use names; aliases such as `cltv`/`nop2`, `csv`/`nop3` and "
   "`ctv`/`nop4` name the same byte, and each consensus value decides what that byte does.\n\n"
   "## In `bitcoin`\n\n| Opcode | Byte | What it does |\n|---|---|---|\n"
   (string-append*
    (for/list ([o (in-list (describe 'opcodes))])
      (format "| `~a` | `0x~a` | ~a |\n" (first o)
              (string-downcase (number->string (third o) 16)) (escape (fourth o)))))
   "\n## Proposal opcodes\n\nOpcodes a consensus can upgrade an upgradable NOP to with `define-consensus`.\n\n"
   "| Opcode | Byte | What it does |\n|---|---|---|\n"
   (string-append*
    (for/list ([name '(ctv)])
      (define d (describe name))
      (format "| `~a` | `0x~a` | ~a |\n" name
              (string-downcase (number->string (cadr (memq '#:byte d)) 16))
              (escape (cadr (memq '#:proposal d))))))))

;; (filename . contents) for every generated page.
(define (reference-pages)
  (list (cons "forms.md" (forms-page))
        (cons "rules.md" (rules-page))
        (cons "opcodes.md" (opcodes-page))))

(module+ main
  (for ([p (in-list (reference-pages))])
    (call-with-output-file (build-path reference-dir (car p)) #:exists 'truncate
      (λ (out) (write-string (cdr p) out)))
    (printf "wrote docs/reference/~a\n" (car p))))
