= ARK
:page-layout: page
:page-title: ARK
:page-nav_order: 2

== Introduction

The ARK protocol is a bitcoin layer 2 proposal that focusses on making
reducing liquidity locking requirements and channel setup requirements
for end users. The trade off is to push the liquidity provision and
management to "ARK Service Providers" - ASPs.

== Overview

The ARK protocol requires a funding transaction which is a 2 of 2
multisig betwen an end user, Alice, and the ASP.

The system state transitions can be succinctly described as:

. Alice onboards with an ASP
.. ASP is non-cooperative and Alice leaves after 1y with her coins
. Alice makes off chain payment to Bob
. Now multiple branches need to exploration:
.. ASP refuses to accept Alice's request to make payment
.. Alice cooperatively reverts and undoes off chain payment
.. Alice unilaterally reverts and undoes off chain payment
.. Bob cooperatively leaves the ARK with received payment
.. Bob unilaterally leaves the ARK with received payment


.State transitions for ARK
[plantuml]
----
@startuml
	Init: alice_coinbase:
	Init: asp_coinbase

	[*] --> FundingTx
	FundingTx --> ConfirmedFundingTx: Broadcast and confirmed on chain
@enduml
----

=== Funding Transaction

The funding transaction can be spent co-operatively by the two parties
signing the funding transaction or by user after a timeout period (say
1 month)

Using Bitcoin DSL we capture the funding transaction output script as
a miniscript policy

.Funding transaction output miniscript policy
[source,ruby]
----
or(99@thresh(2,pk(@alice),pk(@asp)),and(older(10),pk(@asp_timelock)))
----
