= Contract Branch Executions
:page-layout: page
:page-title: Contract Branch Executions
:page-nav_order: 3
:sourcedir: ../../


The DSL makes it easy to run the transactions along the various
execution paths of a contract.

---

The challenge when developing contracts is to execute the various
branches the contracts can execute on. The branches that are executed
depend on the state of the chain and the data provided by the parties
executing the contract transactions. 

With the DSL a developer can declaratively move the state of the
system (bitcoin, transactions and user data) and then execute branches
of their choosing.

We solve this problem by breaking up the contract execution into
multiple scripts and then running the various branches in serial. Each
execution is automatically run in a different chain instance - by
deleting the old chain and starting a new one.

[source,ruby]
----
run_script './setup.rb'

# Run any branch that can be executed after setup has finished.
----

After each branch execution the developer can then run assertions on
the state of the system. See link:/reference#assertions[Assertions]
for all the supported assertions.

The execution paths are best described with an simple contract that
has two branches - a simple timelock contract.

== Example: A timelock contract

Let's say there is a contract where Alice can spend the transaction at
any time and Bob can only spend the transaction after 10 blocks. Using
the miniscript policy `'or(and(older(10),pk(@alice)),pk(@bob))'`. Such a contract
has the following state transitions.

.State transitions for a contract using `'or(and(older(10),pk(@alice)),pk(@bob))'` miniscript policy.
[mermaid]
----
stateDiagram-v2
    [*] --> ConfirmedOnChain

    ConfirmedOnChain --> SpentByBob

    ConfirmedOnChain -->  DelayExpired
    DelayExpired --> SpentByAlice
    DelayExpired --> SpentByBobAfterDelay

    SpentByBob --> [*]
    SpentByAlice --> [*]
    SpentByBobAfterDelay --> [*]
----

The state transition of the contract above shows how even in a simple
contract, we need to be careful when exploring all execution paths. We
need to verify the following behaviours:

1. Bob can immediately spend from confirmation.
2. Bob can spend from confirmation after delay has expired.
3. Alice can not spend before delay has expired.
4. Alice can spend after delay has expired.

The pain point the Bitcoin DSL solves is the ability to run through
all the states and then run assertions at each state about the state
of the system.

== Executing the state transition diagram

The scripts below show how we can transition the system from one state
to the other and then run assertions for the transition.

=== Setup

We first setup the keys, generate a confirmation transaction and get
100 confirmations for it.

[source,ruby]
----
include::{sourcedir}/lib/contracts/example_branch_execution/setup.rb[tags=setup]
----
<1> Use miniscript policy as coinbase
<2> Extend chain such that the coinbase is spendable

=== Bob spends immediately

[source,ruby]
----
include::{sourcedir}/lib/contracts/example_branch_execution/bob_spends_immediately.rb[tags=bob_spends_immediately]
----
<1> Run setup to make this branch executable
<2> Bob signs the transaction to spend it immediately
<3> The spending transaction is broadcast and confirmed

=== Bob spends after delay

[source,ruby]
----
include::{sourcedir}/lib/contracts/example_branch_execution/bob_spends_after_delay.rb[tags=bob_spends_after_delay]
----
<1> Run setup to make this branch executable
<2> Bob signs the transaction to spend it immediately
<3> Extend chain by mining 10 blocks
<4> The spending transaction is broadcast and confirmed


=== Alice can not spend immediately

[source,ruby]
----
include::{sourcedir}/lib/contracts/example_branch_execution/alice_cant_spend_immediately.rb[tags=alice_cant_spend]
----
<1> Run setup to make this branch executable
<2> Alice signs the transaction to spend it immediately
<3> Alice's attempt is spend is not accepted by the mempool

=== Alice can spend after a delay

[source,ruby]
----
include::{sourcedir}/lib/contracts/example_branch_execution/alice_spends_after_delay.rb[tags=alice_spends_after_delay]
----
<1> Run setup to make this branch executable
<2> Alice signs the transaction
<3> Extend chain by mining 10 blocks
<4> Alice's spending transaction is broadcast and confirmed
