name: Docker Image CI
on: push
jobs:
  run-docker-image-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: bitcoin-dsl
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run rake spec
        run: docker run bitcoin-dsl rake spec
  
